### ISSUE TITLE
Cannot attach tags in Sentry 21.2.0

### ISSUE THREAD

**Issue by tlf30** [Biekos/sentry-mattermost#10]
Hello,
First I would like to say thank you for keeping this plugin alive. 

I have run into an issue after updating to Sentry 21.2.0 where enabling attach tags throws an error on publishing a notification: 
```
AttributeError: 'Event' object has no attribute 'get_tags'
  File "sentry/utils/safe.py", line 23, in safe_execute
    result = func(*args, **kwargs)
  File "sentry/plugins/bases/notify.py", line 92, in rule_notify
    self.notify(notification)
  File "sentry/plugins/bases/notify.py", line 60, in notify
    event.group, event, triggering_rules=[r.label for r in notification.rules]
  File "sentry_mattermost/plugin.py", line 176, in notify_users
    self, event, template, triggering_rules)
  File "sentry_mattermost/plugin.py", line 80, in create
    params["tags"] = get_tags(event)
  File "sentry_mattermost/plugin.py", line 39, in get_tags
    tag_list = event.get_tags()
```

Full error report here: https://sentry.liquidcrystalstudios.com/share/issue/e8de7369191b4364a5d485692bffbbb2/

Thanks,
Trevor

**Comment by aurorecr** [comment]
Hi Trevor,

Thank you for your comments and feedback, we really appreciate.

We are now working on the issue you have reported.

Have a wonderful day,

Team Biekos

**Comment by aurorecr** [comment]
Hi Trevor,

It's seems like we have fixed the issue.

Please feel free to double check.

Kind regards,

Team Biekos

**Comment by PXke** [comment]
Dear @tlf30,

Did you by any chance get time to test the latest version?

Have a lovely day. 

My best regards.

**Comment by tlf30** [comment]
@PXke, I have been in the artic circle for the last two weeks! It was cold, we saw -54⁰ F. 

I am currently traveling home. I will test once I get in back.

**Comment by PXke** [comment]
Dear @tlf30 

Enjoy, It sounds like it has been cool and fun.

Have a safe trip 

Best
G.

**Comment by tlf30** [comment]
@aurorecr @PXke I just tested the update, it works great.
Thank you for your work on this.

**Comment by aurorecr** [comment]
Pleasure! Enjoy your trip,

Kind regards,

Aurore
