### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jwillmer** [Biekos/sentry-mattermost#12]
Latest sentry uses python 3 and the plugin fails to load:

![image](https://user-images.githubusercontent.com/1503577/115410854-4879d180-a1f3-11eb-84ac-38f3630b94e1.png)

**Comment by PXke** [comment]
Dear @jwillmer I wanted to take a look at the issue but the code that you are pointing does not exist: 

We replaced urllib2 with requests.

https://github.com/Biekos/sentry-mattermost/blob/master/sentry_mattermost/plugin.py#L22

It should work with python3 :) 

Have a lovely day.
